include:
    - api/compose.yaml

services:
    storyclash:
        build: .
        ports:
            - 8080:80
        depends_on:
            - database
        environment:
            APP_DEMO: true
            DATABASE_URL: "postgresql://app:!ChangeMe!@database:5432/app?serverVersion=16&charset=utf8"
